# Generated by Django 4.0.3 on 2022-04-09 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('agent', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')])),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=1)),
                ('agent', models.ManyToManyField(blank=True, to='fping.agent')),
            ],
        ),
        migrations.CreateModel(
            name='stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample', models.IntegerField(default=0)),
                ('pings', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('median', models.FloatField(default=0)),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=0)),
                ('stdev', models.FloatField(default=0)),
                ('avg_loss', models.IntegerField(default=0)),
                ('avg_median', models.FloatField(default=0)),
                ('avg_min', models.FloatField(default=0)),
                ('avg_max', models.FloatField(default=0)),
                ('avg_stdev', models.FloatField(default=0)),
                ('prev_loss', models.IntegerField(default=0)),
                ('last_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fping.host')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fping.agent')),
            ],
        ),
    ]
